import type { SemanticColors, ThemeDefinition } from '../types.ts'
import {
  DEFAULT_MOTION,
  DENSITY_TOKENS,
  HEADER_HEIGHT_TOKENS,
  MONO_FONT_STACK,
  RADIUS_TOKENS,
  SIDEBAR_WIDTH_TOKENS,
  UI_FONT_STACKS,
} from '../shared-tokens.ts'

const darkColors: SemanticColors = {
  bgBase: '#111318',
  bgSurface: '#191C23',
  bgElevated: '#222630',
  bgOverlay: '#222630',
  bgSidebar: '#0E1016',
  bgHeader: '#111318',
  bgInput: '#151821',
  bgTableHeader: '#151821',
  bgInset: '#151821',
  bgAuth: '#0B0D12',
  textPrimary: '#EEF0F4',
  textSecondary: '#A4ADBC',
  textMuted: '#7B8494',
  border: '#303641',
  borderLight: 'rgba(255, 255, 255, 0.06)',
  borderHover: '#3C4452',
  success: '#22c55e',
  warning: '#f59e0b',
  danger: '#ef4444',
  info: '#3b82f6',
}

const lightColors: SemanticColors = {
  bgBase: '#E4E6EC',
  bgSurface: '#F4F5F8',
  bgElevated: '#FAFBFC',
  bgOverlay: '#FFFFFF',
  bgSidebar: '#D8DCE4',
  bgHeader: '#ECEEF3',
  bgInput: '#F7F8FB',
  bgTableHeader: '#E8EAEE',
  bgInset: '#E6E8EE',
  bgAuth: '#D5D9E2',
  textPrimary: '#141820',
  textSecondary: '#3A4250',
  textMuted: '#5B6472',
  border: '#C3C9D4',
  borderLight: '#D3D8E1',
  borderHover: '#A7B0BD',
  success: '#15803d',
  warning: '#b45309',
  danger: '#b91c1c',
  info: '#1d4ed8',
}

export const atelierTheme: ThemeDefinition = {
  schemaVersion: 1,
  id: 'atelier',
  name: '工坊',
  version: '1.1.0',
  modes: {
    dark: {
      colors: darkColors,
      accentKey: 'vermilion',
      terminalTheme: 'default',
      editorTheme: 'vs-dark',
    },
    light: {
      colors: lightColors,
      accentKey: 'steel',
      terminalTheme: 'paper',
      editorTheme: 'vs',
    },
  },
  defaults: {
    mode: 'dark',
    density: 'default',
    uiFont: 'lxgw',
    sidebarWidth: 'default',
    headerHeight: 'default',
    radius: 'default',
    reduceMotion: false,
    transparency: false,
    iconSet: 'outline',
    termFont: 'consolas',
    termFontSize: 14,
    termBgOpacity: 0.5,
    chromeTexture: 'ribbon',
  },
  tokens: {
    fonts: { ui: UI_FONT_STACKS, mono: MONO_FONT_STACK },
    materials: {
      transparency: false,
      surfaceOpacity: 0.88,
      blurPx: 12,
      sidebarOpacity: 0.78,
      headerOpacity: 0.82,
      overlayOpacity: 0.9,
    },
    shapes: RADIUS_TOKENS,
    motion: DEFAULT_MOTION,
    densities: DENSITY_TOKENS,
    sidebarWidths: SIDEBAR_WIDTH_TOKENS,
    headerHeights: HEADER_HEIGHT_TOKENS,
  },
  variants: {
    sidebar: 'marker',
    subnav: 'block',
    card: 'outline',
    iconContainer: 'none',
  },
  iconSet: 'outline',
  terminal: { dark: 'default', light: 'paper' },
  editor: { dark: 'vs-dark', light: 'vs' },
  charts: {
    categorical: ['#7AA2FF', '#34d399', '#fbbf24', '#fb7185', '#a78bfa', '#22d3ee'],
    sequential: ['#2A4CA3', '#355FCC', '#5B86E8', '#7AA2FF', '#9DB8FF'],
  },
  surfaces: { cardTopEdge: true, hoverStrength: 1 },
}
