import type { SemanticColors, ThemeDefinition } from '../types.ts'
import {
  DEFAULT_MOTION,
  DENSITY_TOKENS,
  HEADER_HEIGHT_TOKENS,
  MONO_FONT_STACK,
  RADIUS_TOKENS,
  SIDEBAR_WIDTH_TOKENS,
  UI_FONT_STACKS,
} from '../shared-tokens.ts'

const darkColors: SemanticColors = {
  bgBase: '#053035',
  bgSurface: '#0A3D44',
  bgElevated: '#125058',
  bgOverlay: '#165860',
  bgSidebar: '#032428',
  bgHeader: '#053035',
  bgInput: '#08363C',
  bgTableHeader: '#08363C',
  bgInset: '#08363C',
  bgAuth: '#02181B',
  textPrimary: '#E4F7F5',
  textSecondary: '#A8D0CC',
  textMuted: '#8FB3B0',
  border: '#1A5A62',
  borderLight: 'rgba(228, 247, 245, 0.08)',
  borderHover: '#2A6E76',
  success: '#4AAE8A',
  warning: '#C9A35B',
  danger: '#D07060',
  info: '#6AA8B0',
}

const lightColors: SemanticColors = {
  bgBase: '#D5E8E6',
  bgSurface: '#F2FAF8',
  bgElevated: '#FBFFFE',
  bgOverlay: '#FFFFFF',
  bgSidebar: '#B7D0CC',
  bgHeader: '#E3F2F0',
  bgInput: '#E8F4F2',
  bgTableHeader: '#D0E4E1',
  bgInset: '#D0E4E1',
  bgAuth: '#C5DCD8',
  textPrimary: '#0E2A2C',
  textSecondary: '#2F5558',
  textMuted: '#4A6C6E',
  border: '#A8C4C0',
  borderLight: '#C5D9D6',
  borderHover: '#8AADA8',
  success: '#1F6F6E',
  warning: '#8A6A1A',
  danger: '#A94438',
  info: '#1F6F6E',
}

export const harborTheme: ThemeDefinition = {
  schemaVersion: 1,
  id: 'harbor',
  name: '港湾',
  version: '1.0.0',
  source: 'builtin',
  modes: {
    dark: {
      colors: darkColors,
      accentKey: 'brass',
      terminalTheme: 'solarized',
      editorTheme: 'vs-dark',
    },
    light: {
      colors: lightColors,
      accentKey: 'tide',
      terminalTheme: 'paper',
      editorTheme: 'vs',
    },
  },
  defaults: {
    mode: 'dark',
    density: 'default',
    uiFont: 'noto',
    sidebarWidth: 'default',
    headerHeight: 'default',
    radius: 'default',
    reduceMotion: false,
    transparency: true,
    iconSet: 'solid',
    termFont: 'jetbrains',
    termFontSize: 14,
    termBgOpacity: 0.72,
    chromeTexture: 'galaxy',
  },
  tokens: {
    fonts: { ui: UI_FONT_STACKS, mono: MONO_FONT_STACK },
    materials: {
      transparency: true,
      surfaceOpacity: 0.86,
      blurPx: 16,
      sidebarOpacity: 0.82,
      headerOpacity: 0.8,
      overlayOpacity: 0.92,
    },
    shapes: RADIUS_TOKENS,
    motion: { ...DEFAULT_MOTION, hoverMs: 110, menuMs: 150 },
    densities: DENSITY_TOKENS,
    sidebarWidths: SIDEBAR_WIDTH_TOKENS,
    headerHeights: HEADER_HEIGHT_TOKENS,
  },
  variants: {
    sidebar: 'rail',
    subnav: 'line',
    card: 'raised',
    iconContainer: 'tile',
    heading: 'compact',
  },
  iconSet: 'solid',
  terminal: { dark: 'solarized', light: 'paper' },
  editor: { dark: 'vs-dark', light: 'vs' },
  charts: {
    categorical: ['#C9A35B', '#3D9A96', '#E7F1F2', '#D07060', '#6AA8B0', '#4AAE8A'],
    sequential: ['#081012', '#0B1517', '#1F6F6E', '#3D9A96', '#7EB6B4'],
  },
  surfaces: { cardTopEdge: true, hoverStrength: 1 },
}
