import type { SemanticColors, ThemeDefinition } from '../types.ts'
import {
  DEFAULT_MOTION,
  DENSITY_TOKENS,
  HEADER_HEIGHT_TOKENS,
  MONO_FONT_STACK,
  RADIUS_TOKENS,
  SIDEBAR_WIDTH_TOKENS,
  UI_FONT_STACKS,
} from '../shared-tokens.ts'

const darkColors: SemanticColors = {
  bgBase: '#1C130C',
  bgSurface: '#271C12',
  bgElevated: '#332418',
  bgOverlay: '#3B2B1C',
  bgSidebar: '#100B07',
  bgHeader: '#1C130C',
  bgInput: '#21180F',
  bgTableHeader: '#21180F',
  bgInset: '#21180F',
  bgAuth: '#0C0805',
  textPrimary: '#F7ECD8',
  textSecondary: '#C9B496',
  textMuted: '#A09078',
  border: '#4A3C2E',
  borderLight: 'rgba(247, 236, 216, 0.08)',
  borderHover: '#5E4C3A',
  success: '#6FAE86',
  warning: '#C4A35A',
  danger: '#C45C4A',
  info: '#8A9AA0',
}

const lightColors: SemanticColors = {
  bgBase: '#E8DCC4',
  bgSurface: '#FBF3E3',
  bgElevated: '#FFF8EC',
  bgOverlay: '#FFF8EC',
  bgSidebar: '#D4C4A8',
  bgHeader: '#F3E8D2',
  bgInput: '#F6EDDC',
  bgTableHeader: '#EDE1CA',
  bgInset: '#EDE1CA',
  bgAuth: '#DCCEB4',
  textPrimary: '#1C140C',
  textSecondary: '#5C4E3C',
  textMuted: '#6E5E48',
  border: '#C9B896',
  borderLight: '#E0D2B4',
  borderHover: '#B09A74',
  success: '#2F6B4A',
  warning: '#8A6A1A',
  danger: '#9A3F32',
  info: '#3D4E63',
}

export const inkTheme: ThemeDefinition = {
  schemaVersion: 1,
  id: 'ink',
  name: '墨池',
  version: '1.0.0',
  source: 'builtin',
  modes: {
    dark: {
      colors: darkColors,
      accentKey: 'pine',
      terminalTheme: 'default',
      editorTheme: 'vs-dark',
    },
    light: {
      colors: lightColors,
      accentKey: 'pine-deep',
      terminalTheme: 'paper',
      editorTheme: 'vs',
    },
  },
  defaults: {
    mode: 'dark',
    density: 'default',
    uiFont: 'lxgw',
    sidebarWidth: 'default',
    headerHeight: 'default',
    radius: 'sharp',
    reduceMotion: false,
    transparency: false,
    iconSet: 'outline',
    termFont: 'consolas',
    termFontSize: 14,
    termBgOpacity: 0.62,
    chromeTexture: 'grain',
  },
  tokens: {
    fonts: { ui: UI_FONT_STACKS, mono: MONO_FONT_STACK },
    materials: {
      transparency: false,
      surfaceOpacity: 0.92,
      blurPx: 10,
      sidebarOpacity: 0.88,
      headerOpacity: 0.9,
      overlayOpacity: 0.94,
    },
    shapes: RADIUS_TOKENS,
    motion: DEFAULT_MOTION,
    densities: DENSITY_TOKENS,
    sidebarWidths: SIDEBAR_WIDTH_TOKENS,
    headerHeights: HEADER_HEIGHT_TOKENS,
  },
  variants: {
    sidebar: 'marker',
    subnav: 'line',
    card: 'outline',
    iconContainer: 'tile',
    heading: 'display',
  },
  iconSet: 'outline',
  terminal: { dark: 'default', light: 'paper' },
  editor: { dark: 'vs-dark', light: 'vs' },
  charts: {
    categorical: ['#6FAE86', '#C4B7A2', '#C45C4A', '#7A8F9A', '#C4A35A', '#8A7A62'],
    sequential: ['#163626', '#1C4430', '#2F6B4A', '#3D7A5A', '#6FAE86'],
  },
  surfaces: { cardTopEdge: true, hoverStrength: 0.8 },
}
