import type { SemanticColors, ThemeDefinition } from '../types.ts'
import {
  DEFAULT_MOTION,
  DENSITY_TOKENS,
  HEADER_HEIGHT_TOKENS,
  MONO_FONT_STACK,
  RADIUS_TOKENS,
  SIDEBAR_WIDTH_TOKENS,
  UI_FONT_STACKS,
} from '../shared-tokens.ts'

const darkColors: SemanticColors = {
  bgBase: '#16131A',
  bgSurface: '#221E28',
  bgElevated: '#2C2733',
  bgOverlay: '#322C3A',
  bgSidebar: '#1A1620',
  bgHeader: '#1A1620',
  bgInput: '#1C1822',
  bgTableHeader: '#1C1822',
  bgInset: '#1C1822',
  bgAuth: '#120F16',
  textPrimary: '#F4EEE6',
  textSecondary: '#C4B8A8',
  textMuted: '#8F8478',
  border: '#3A3342',
  borderLight: 'rgba(244, 238, 230, 0.08)',
  borderHover: '#52485A',
  success: '#4ade80',
  warning: '#fbbf24',
  danger: '#fb7185',
  info: '#67e8f9',
}

const lightColors: SemanticColors = {
  bgBase: '#F4EFE6',
  bgSurface: '#FFFBF4',
  bgElevated: '#FFFBF4',
  bgOverlay: '#FFFBF4',
  bgSidebar: '#EFE6D8',
  bgHeader: '#FFF9F0',
  bgInput: '#FFFBF4',
  bgTableHeader: '#F3EADF',
  bgInset: '#F3EADF',
  bgAuth: '#EBE3D4',
  textPrimary: '#1A1714',
  textSecondary: '#5C5348',
  textMuted: '#8A7F72',
  border: '#D2C3B0',
  borderLight: '#E2D6C6',
  borderHover: '#B9A890',
  success: '#15803d',
  warning: '#b45309',
  danger: '#b91c1c',
  info: '#0f766e',
}

export const lumenTheme: ThemeDefinition = {
  schemaVersion: 1,
  id: 'lumen',
  name: '流光',
  version: '1.0.0',
  modes: {
    dark: {
      colors: darkColors,
      accentKey: 'orange',
      terminalTheme: 'lumen-dark',
      editorTheme: 'vs-dark',
    },
    light: {
      colors: lightColors,
      accentKey: 'orange',
      terminalTheme: 'lumen-light',
      editorTheme: 'vs',
    },
  },
  defaults: {
    mode: 'dark',
    density: 'default',
    uiFont: 'noto',
    sidebarWidth: 'default',
    headerHeight: 'comfortable',
    radius: 'rounded',
    reduceMotion: false,
    transparency: true,
    iconSet: 'solid',
    termFont: 'jetbrains',
    termFontSize: 14,
    termBgOpacity: 1,
    chromeTexture: 'none',
  },
  tokens: {
    fonts: { ui: UI_FONT_STACKS, mono: MONO_FONT_STACK },
    materials: {
      transparency: true,
      surfaceOpacity: 0.88,
      blurPx: 14,
      sidebarOpacity: 0.86,
      headerOpacity: 0.82,
      overlayOpacity: 0.94,
    },
    shapes: RADIUS_TOKENS,
    motion: { ...DEFAULT_MOTION, hoverMs: 120, menuMs: 160, drawerMs: 200 },
    densities: DENSITY_TOKENS,
    sidebarWidths: SIDEBAR_WIDTH_TOKENS,
    headerHeights: HEADER_HEIGHT_TOKENS,
  },
  variants: {
    sidebar: 'block',
    subnav: 'pill',
    card: 'raised',
    iconContainer: 'tile',
  },
  iconSet: 'solid',
  terminal: { dark: 'lumen-dark', light: 'lumen-light' },
  editor: { dark: 'vs-dark', light: 'vs' },
  charts: {
    categorical: ['#E08A4A', '#2DD4BF', '#F4EEE6', '#C084FC', '#F87171', '#FBBF24'],
    sequential: ['#9A3412', '#C2410C', '#EA580C', '#FB923C', '#FDBA74'],
  },
  surfaces: { cardTopEdge: true, hoverStrength: 1 },
}
