import type { SemanticColors, ThemeDefinition } from '../types.ts'
import {
  DEFAULT_MOTION,
  DENSITY_TOKENS,
  HEADER_HEIGHT_TOKENS,
  MONO_FONT_STACK,
  RADIUS_TOKENS,
  SIDEBAR_WIDTH_TOKENS,
  UI_FONT_STACKS,
} from '../shared-tokens.ts'

const darkColors: SemanticColors = {
  bgBase: '#08090C',
  bgSurface: '#12151C',
  bgElevated: '#1B202A',
  bgOverlay: '#242A36',
  bgSidebar: '#050608',
  bgHeader: '#08090C',
  bgInput: '#0E1116',
  bgTableHeader: '#0E1116',
  bgInset: '#0E1116',
  bgAuth: '#040506',
  textPrimary: '#F5F7FB',
  textSecondary: '#B0B8C6',
  textMuted: '#8E96A6',
  border: '#2A3140',
  borderLight: 'rgba(245, 247, 251, 0.06)',
  borderHover: '#3A4254',
  success: '#5B9A74',
  warning: '#C4A35A',
  danger: '#C45C5C',
  info: '#8FA6BC',
}

const lightColors: SemanticColors = {
  bgBase: '#DCE1EA',
  bgSurface: '#F7F8FB',
  bgElevated: '#FCFCFD',
  bgOverlay: '#FFFFFF',
  bgSidebar: '#B4BCC8',
  bgHeader: '#E8ECF2',
  bgInput: '#EEF1F6',
  bgTableHeader: '#E0E4EC',
  bgInset: '#E0E4EC',
  bgAuth: '#CDD4DE',
  textPrimary: '#12141A',
  textSecondary: '#3A4150',
  textMuted: '#5A6270',
  border: '#B8C0CC',
  borderLight: '#D2D8E2',
  borderHover: '#9AA4B2',
  success: '#2F6B4A',
  warning: '#8A6A1A',
  danger: '#9A3F3F',
  info: '#3D4E63',
}

export const quartzTheme: ThemeDefinition = {
  schemaVersion: 1,
  id: 'quartz',
  name: '石英',
  version: '1.0.0',
  source: 'builtin',
  modes: {
    dark: {
      colors: darkColors,
      accentKey: 'slate',
      terminalTheme: 'onedark',
      editorTheme: 'vs-dark',
    },
    light: {
      colors: lightColors,
      accentKey: 'slate-deep',
      terminalTheme: 'paper',
      editorTheme: 'vs',
    },
  },
  defaults: {
    mode: 'dark',
    density: 'comfortable',
    uiFont: 'system',
    sidebarWidth: 'default',
    headerHeight: 'comfortable',
    radius: 'sharp',
    reduceMotion: false,
    transparency: false,
    iconSet: 'outline',
    termFont: 'cascadia',
    termFontSize: 14,
    termBgOpacity: 0.85,
    chromeTexture: 'starfield',
  },
  tokens: {
    fonts: { ui: UI_FONT_STACKS, mono: MONO_FONT_STACK },
    materials: {
      transparency: false,
      surfaceOpacity: 0.94,
      blurPx: 8,
      sidebarOpacity: 0.92,
      headerOpacity: 0.94,
      overlayOpacity: 0.96,
    },
    shapes: RADIUS_TOKENS,
    motion: { ...DEFAULT_MOTION, hoverMs: 80, menuMs: 120 },
    densities: DENSITY_TOKENS,
    sidebarWidths: SIDEBAR_WIDTH_TOKENS,
    headerHeights: HEADER_HEIGHT_TOKENS,
  },
  variants: {
    sidebar: 'marker',
    subnav: 'block',
    card: 'flat',
    iconContainer: 'none',
    heading: 'compact',
  },
  iconSet: 'outline',
  terminal: { dark: 'onedark', light: 'paper' },
  editor: { dark: 'vs-dark', light: 'vs' },
  charts: {
    categorical: ['#8FA6BC', '#C4A35A', '#5B9A74', '#C45C5C', '#A8AEB8', '#B7A99A'],
    sequential: ['#101218', '#1C2028', '#3D4E63', '#4A5D74', '#8FA6BC'],
  },
  surfaces: { cardTopEdge: false, hoverStrength: 0.7 },
}
