package haproxy

import (
	"fmt"
	"sort"
	"strings"

	"xpanel/app/model"
)

// Settings 生成配置所需的全局参数
type Settings struct {
	GlobalLog    string // "127.0.0.1 local0"
	SocketPath   string // "/run/haproxy/admin.sock"
	StatsEnable  bool
	StatsBind    string // "127.0.0.1:9999"
	StatsURI     string // "/stats"
	StatsUser    string
	StatsPass    string
	MaxConn      int
	DefaultUser  string // 默认 "haproxy"
	DefaultGroup string
}

// BuilderInput 生成配置的全部输入
type BuilderInput struct {
	Settings Settings
	LBs      []model.HAProxyLB
	Backends []model.HAProxyBackend
	Servers  map[uint][]model.HAProxyServer
	ACLs     map[uint][]model.HAProxyACLRule
	// CertPathFor 返回 LB 所关联的 PEM 文件路径（合并 cert+key 后的 haproxy 专用 PEM）
	CertPathFor func(lb model.HAProxyLB) string
}

// Build 根据输入数据生成完整的 haproxy.cfg
func Build(in BuilderInput) string {
	var sb strings.Builder
	writeGlobal(&sb, in.Settings)
	writeDefaults(&sb, in.Settings)

	// Frontend（来自 LB）
	sortedLBs := make([]model.HAProxyLB, len(in.LBs))
	copy(sortedLBs, in.LBs)
	sort.Slice(sortedLBs, func(i, j int) bool { return sortedLBs[i].Name < sortedLBs[j].Name })
	for _, lb := range sortedLBs {
		if !lb.Enabled {
			continue
		}
		writeFrontend(&sb, lb, in)
	}

	// Backend
	sortedBEs := make([]model.HAProxyBackend, len(in.Backends))
	copy(sortedBEs, in.Backends)
	sort.Slice(sortedBEs, func(i, j int) bool { return sortedBEs[i].Name < sortedBEs[j].Name })
	for _, be := range sortedBEs {
		writeBackend(&sb, be, in.Servers[be.ID])
	}

	// Stats 内部监听
	if in.Settings.StatsEnable {
		writeStatsListen(&sb, in.Settings)
	}
	return sb.String()
}

func writeGlobal(sb *strings.Builder, s Settings) {
	maxconn := s.MaxConn
	if maxconn <= 0 {
		maxconn = 50000
	}
	user := s.DefaultUser
	if user == "" {
		user = "haproxy"
	}
	group := s.DefaultGroup
	if group == "" {
		group = "haproxy"
	}
	sock := s.SocketPath
	if sock == "" {
		sock = DefaultSocketPath
	}
	logTgt := s.GlobalLog
	if logTgt == "" {
		logTgt = "127.0.0.1 local0"
	}
	sb.WriteString("# Generated by X-Panel. Do not edit manually unless you know what you are doing.\n")
	sb.WriteString("\n")
	sb.WriteString("global\n")
	fmt.Fprintf(sb, "    log %s\n", logTgt)
	fmt.Fprintf(sb, "    maxconn %d\n", maxconn)
	fmt.Fprintf(sb, "    stats socket %s mode 660 level admin expose-fd listeners\n", sock)
	sb.WriteString("    stats timeout 30s\n")
	fmt.Fprintf(sb, "    user %s\n", user)
	fmt.Fprintf(sb, "    group %s\n", group)
	sb.WriteString("    daemon\n")
	sb.WriteString("    ssl-default-bind-options no-sslv3 no-tlsv10 no-tlsv11\n")
	sb.WriteString("    ssl-default-bind-ciphersuites TLS_AES_128_GCM_SHA256:TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256\n")
	sb.WriteString("\n")
}

func writeDefaults(sb *strings.Builder, s Settings) {
	sb.WriteString("defaults\n")
	sb.WriteString("    log     global\n")
	sb.WriteString("    option  dontlognull\n")
	sb.WriteString("    option  redispatch\n")
	sb.WriteString("    retries 3\n")
	sb.WriteString("    timeout connect 5s\n")
	sb.WriteString("    timeout client  30s\n")
	sb.WriteString("    timeout server  30s\n")
	sb.WriteString("    timeout http-request 10s\n")
	sb.WriteString("    timeout http-keep-alive 2s\n")
	sb.WriteString("\n")
}

func writeFrontend(sb *strings.Builder, lb model.HAProxyLB, in BuilderInput) {
	fmt.Fprintf(sb, "frontend %s\n", lb.Name)
	fmt.Fprintf(sb, "    mode %s\n", safeMode(lb.Mode))
	// bind
	bindAddr := lb.BindAddr
	if bindAddr == "" {
		bindAddr = "0.0.0.0"
	}
	bindLine := fmt.Sprintf("    bind %s:%d", bindAddr, lb.BindPort)
	if lb.EnableSSL && in.CertPathFor != nil {
		if pem := in.CertPathFor(lb); pem != "" {
			bindLine += " ssl crt " + pem
			bindLine += " alpn h2,http/1.1"
		}
	}
	bindLine += "\n"
	sb.WriteString(bindLine)

	// maxconn / timeouts
	if lb.MaxConn > 0 {
		fmt.Fprintf(sb, "    maxconn %d\n", lb.MaxConn)
	}
	if lb.TimeoutClient > 0 {
		fmt.Fprintf(sb, "    timeout client %ds\n", lb.TimeoutClient)
	}

	if safeMode(lb.Mode) == "http" {
		sb.WriteString("    option httplog\n")
		if lb.XForwardedFor {
			sb.WriteString("    option forwardfor\n")
			sb.WriteString("    http-request set-header X-Forwarded-Proto https if { ssl_fc }\n")
			sb.WriteString("    http-request set-header X-Forwarded-Proto http unless { ssl_fc }\n")
		}
		if lb.SSLRedirect && lb.EnableSSL {
			sb.WriteString("    http-request redirect scheme https code 301 unless { ssl_fc }\n")
		}

		// ACL 路由
		acls := in.ACLs[lb.ID]
		sort.Slice(acls, func(i, j int) bool { return acls[i].Priority < acls[j].Priority })
		beNameMap := make(map[uint]string, len(in.Backends))
		for _, be := range in.Backends {
			beNameMap[be.ID] = be.Name
		}
		for idx, acl := range acls {
			if !acl.Enabled {
				continue
			}
			aclName := fmt.Sprintf("acl_rule_%d", idx)
			switch acl.MatchType {
			case "host":
				fmt.Fprintf(sb, "    acl %s hdr(host) -i %s\n", aclName, acl.MatchValue)
			case "host_end":
				fmt.Fprintf(sb, "    acl %s hdr_end(host) -i %s\n", aclName, acl.MatchValue)
			case "path_beg":
				fmt.Fprintf(sb, "    acl %s path_beg %s\n", aclName, acl.MatchValue)
			case "path_end":
				fmt.Fprintf(sb, "    acl %s path_end %s\n", aclName, acl.MatchValue)
			case "path_reg":
				fmt.Fprintf(sb, "    acl %s path_reg %s\n", aclName, acl.MatchValue)
			case "hdr":
				header := acl.MatchHeader
				if header == "" {
					header = "host"
				}
				fmt.Fprintf(sb, "    acl %s hdr(%s) -i %s\n", aclName, header, acl.MatchValue)
			case "src":
				fmt.Fprintf(sb, "    acl %s src %s\n", aclName, acl.MatchValue)
			}
			if be, ok := beNameMap[acl.TargetBackendID]; ok {
				fmt.Fprintf(sb, "    use_backend %s if %s\n", be, aclName)
			}
		}
	}

	// default backend
	for _, be := range in.Backends {
		if be.ID == lb.DefaultBackendID {
			fmt.Fprintf(sb, "    default_backend %s\n", be.Name)
			break
		}
	}
	sb.WriteString("\n")
}

func writeBackend(sb *strings.Builder, be model.HAProxyBackend, servers []model.HAProxyServer) {
	fmt.Fprintf(sb, "backend %s\n", be.Name)
	fmt.Fprintf(sb, "    mode %s\n", safeMode(be.Mode))
	balance := be.Balance
	if balance == "" {
		balance = "roundrobin"
	}
	fmt.Fprintf(sb, "    balance %s\n", balance)

	// sticky
	switch be.StickyType {
	case "cookie":
		name := be.StickyName
		if name == "" {
			name = "SRVID"
		}
		fmt.Fprintf(sb, "    cookie %s insert indirect nocache\n", name)
	case "source":
		// balance source 已经处理了，这里无需额外
	}

	// 健康检查
	switch be.HealthType {
	case "http":
		method := be.HealthMethod
		if method == "" {
			method = "GET"
		}
		path := be.HealthPath
		if path == "" {
			path = "/"
		}
		if be.HealthHost != "" {
			fmt.Fprintf(sb, "    option httpchk %s %s HTTP/1.1\\r\\nHost:\\ %s\n", method, path, be.HealthHost)
		} else {
			fmt.Fprintf(sb, "    option httpchk %s %s\n", method, path)
		}
		if be.HealthExpect != "" {
			fmt.Fprintf(sb, "    http-check expect %s\n", be.HealthExpect)
		}
	case "mysql":
		sb.WriteString("    option mysql-check\n")
	case "pgsql":
		sb.WriteString("    option pgsql-check user postgres\n")
	case "redis":
		sb.WriteString("    option tcp-check\n")
		sb.WriteString("    tcp-check send PING\\r\\n\n")
		sb.WriteString("    tcp-check expect string +PONG\n")
	case "ssl-hello":
		sb.WriteString("    option ssl-hello-chk\n")
	case "tcp", "":
		// 默认 tcp check（仅探活端口）
	case "none":
		// 不检查
	}

	// server 列表
	for _, srv := range servers {
		line := fmt.Sprintf("    server %s %s:%d", srv.Name, srv.Address, srv.Port)
		if be.HealthType != "none" {
			inter := be.HealthInter
			if inter <= 0 {
				inter = 2000
			}
			rise := be.HealthRise
			if rise <= 0 {
				rise = 2
			}
			fall := be.HealthFall
			if fall <= 0 {
				fall = 3
			}
			line += fmt.Sprintf(" check inter %d rise %d fall %d", inter, rise, fall)
		}
		w := srv.Weight
		if w <= 0 {
			w = 100
		}
		line += fmt.Sprintf(" weight %d", w)
		if srv.MaxConn > 0 {
			line += fmt.Sprintf(" maxconn %d", srv.MaxConn)
		}
		if srv.Backup {
			line += " backup"
		}
		if srv.Disabled {
			line += " disabled"
		}
		if srv.SSL {
			line += " ssl"
			if !srv.SSLVerify {
				line += " verify none"
			}
		}
		if be.StickyType == "cookie" {
			line += " cookie " + srv.Name
		}
		line += "\n"
		sb.WriteString(line)
	}
	sb.WriteString("\n")
}

func writeStatsListen(sb *strings.Builder, s Settings) {
	bind := s.StatsBind
	if bind == "" {
		bind = "127.0.0.1:9999"
	}
	uri := s.StatsURI
	if uri == "" {
		uri = "/stats"
	}
	sb.WriteString("listen xpanel-stats\n")
	fmt.Fprintf(sb, "    bind %s\n", bind)
	sb.WriteString("    mode http\n")
	sb.WriteString("    stats enable\n")
	fmt.Fprintf(sb, "    stats uri %s\n", uri)
	sb.WriteString("    stats refresh 10s\n")
	sb.WriteString("    stats admin if TRUE\n")
	if s.StatsUser != "" && s.StatsPass != "" {
		fmt.Fprintf(sb, "    stats auth %s:%s\n", s.StatsUser, s.StatsPass)
	}
	sb.WriteString("\n")
}

func safeMode(m string) string {
	if m == "tcp" {
		return "tcp"
	}
	return "http"
}
